apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  repositories: |
    - url: https://github.com/lcostea/argocd-config.git
    - name: stable
      type: helm
      url: https://charts.helm.sh/stable
    - name: bitnami
      type: helm
      url: https://charts.bitnami.com/bitnami
