apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

bases:
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=v1.8.3

resources:
- resources/argocd-ns.yaml

patchesStrategicMerge:
- patches/argocd-cm.yaml
- patches/argocd-dex-deployment.yaml
