apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-cluster-root
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: dev-cluster-root
  source:
    path: apps
    repoURL: https://github.com/lcostea/argocd-deploys.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
